import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import WhatsAppButton from "@/Components/WhatsAppButton/WhatsAppButton";
import CartSync from "@/Components/CartSync/CartSync";

export const metadata = {
  title: "Tekpatl",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <CartSync></CartSync>
        <Header></Header>
        {children}
        <Footer></Footer>
        <WhatsAppButton></WhatsAppButton>
      </body>
    </html>
  );
}
